version: "2"
services:
  db:
    image: mariadb:latest
    ports:
    - "3306:3306"
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=project